The worst code you've ever seen.
imanovmarat/burger pull request #4
Opened 2021-07-24 13:32 UTC by imanovmarat

The worst code you've ever seen.

2021-07-25 10:48 UTC, AygulMalikova requested changes
Хорошая работа! У вас структурированный и чистый код, разделенный на компоненты.

Но есть небольшие замечания. В первую очередь прошу вас обратить внимание, что необходимо добавить функционал по удалению ингредиентов из конструктора. Пожалуйста, проверьте, чтобы можно было создать заказ. И также, были оставлены другие комментарии и рекомендации по улучшению вашего кода.

Я напоминаю, что работа будет принята, как только все критические ошибки будут исправлены. Желаю вам удачи!

2021-07-25 10:48 UTC, AygulMalikova commented on src/components/App/App.tsx
>  import OrderDetails from "../OrderDetails/OrderDetails";
Надо исправить:

На данный момент невозможно оформить заказ, т.к. массив ingredients, который вы отправляете на апи при создании заказа, не содержит в себе id ингредиентов. Пожалуйста, исправьте, чтобы id ингредиентов добавлялись в массив

2021-07-25 10:48 UTC, AygulMalikova commented on src/services/actions/index.js
> +export const DELETE_ITEM = 'DELETE_ITEM';
Надо исправить:

По условиям задания: Пользователь может нажать на иконку удаления ингредиента в компоненте BurgerConstructor. Ингредиент удалится из BurgerConstructor, а счётчик количества ингредиентов в компоненте BurgerIngredients уменьшится на один.

На данный момент при нажатии на кнопку удаления ничего не происходит

2021-07-25 10:48 UTC, AygulMalikova commented on src/services/reducers/modal.js
> +    case INGREDIENT_DETAILS_SET_STATUS: {
Надо исправить:

В данном кейсе нет необходимости, т.к. вы можете узнавать статус модального окна с помощью `selectedIngredient`. При открытии модального окна вы устанавливаете значение `selectedIngredient`, а при закрытии его следует удалять. Тем самым вы сможете узнать состояние попапа

2021-07-25 10:48 UTC, AygulMalikova commented on src/services/actions/index.js
> +  };
Надо исправить:

Каждый запрос должен иметь блок catch для обработки ошибок в случае их возникновения. Пожалуйста, добавьте ко всем запросам, где этот блок пропущен

2021-07-25 10:48 UTC, AygulMalikova commented on src/services/reducers/index.js
> +    case CHANGE_SELECTED_INGREDIENTS_ORDER: {
Надо исправить:

Данный кейс следует вынести в отдельный редьюсер, т.к. он относится уже не к ингредиентам бургера (левая колонка), а к конструктору (правая колонка). Туда же следует переместить ADD_SELECTED_INGREDIENT и REMOVE_SELECTED_INGREDIENT

2021-07-25 10:48 UTC, AygulMalikova commented on src/services/reducers/index.js
> +    case GET_SELECTED_INGREDIENTS: {
Можно лучше:

Данный кейс не используется. Если после исправления ошибок он по-прежнему будет не нужен, то его можно будет удалить

2021-07-25 10:48 UTC, AygulMalikova commented on src/components/App/App.tsx
> +  const handleDrop = (itemData:any) => {
Надо исправить:

Обратите внимание, что при изменении порядка ингредиентов внутри конструктора вызывается ADD_SELECTED_INGREDIENT, в связи с чем в массив selectedIngredients добавляется объект, например {index: 1} https://prnt.sc/1fngpim. При изменении порядка ингредиенты не должны добавляться в selectedIngredients

2021-07-25 10:48 UTC, AygulMalikova commented on src/components/App/App.tsx
>    const [isIngredientDetailsModalOpen, setIsIngredientDetailsModalOpen] = useState(false)
Можно лучше:

Не используемые стейты следует удалять

2021-07-25 10:48 UTC, AygulMalikova commented on src/components/App/App.tsx
> +    console.log('itemId ', itemData)
Можно лучше:
Перед отправкой работы, пожалуйста, убедитесь в том, что все строки кода содержащие debugger и console.log удалены.

2021-07-25 10:48 UTC, AygulMalikova commented on src/components/DraggableCard/DraggableCard.js
> +
Надо исправить:

Очень важно иметь правильно отформатированный код для улучшения его читабельности. Пожалуйста, обратитесь к данной статье для изучения стандартов https://learn.javascript.ru/coding-style

Если вы используете IDE (например, VS code), то вы можете автоматически форматировать ваш код:
 https://stackoverflow.com/questions/29973357/how-do-you-format-code-in-visual-studio-code-vscode

2021-07-25 10:48 UTC, AygulMalikova commented on src/components/IngredientDetails/IngredientDetails.js
Надо исправить:

https://github.com/imanovmarat/burger/pull/4/files#diff-d5cf6a2f93db66918281868af77177d9ca819bd99b5f11ad21e3bf7e7bded9f7R29

Как вы можете заметить, тип ингредиента дублируется в нескольких компонентах. Представьте, что в один момент необходимо будет добавить/удалить/изменить одно поле, и тогда это придется делать в нескольких местах. Это нарушает принцип DRY (про него можно почитать в этой статье https://habr.com/ru/post/144611/). Вам следует вынести в отдельный тип, разместить его внутри utils и импортировать внутри компонентов, где он используется.

2021-07-25 10:48 UTC, AygulMalikova commented on src/components/App/App.tsx
> +            <IngredientsContext.Provider value={ingredients}>
Надо исправить:

Сейчас вы используете Redux, поэтому в контексте больше нет необходимости. Его следует удалить

2021-07-26 09:43 UTC, imanovmarat commented on src/components/App/App.tsx
>  import OrderDetails from "../OrderDetails/OrderDetails";
Сделано 👌

2021-07-26 13:35 UTC, imanovmarat commented on src/services/actions/index.js
> +export const DELETE_ITEM = 'DELETE_ITEM';
Сделано 👌

2021-07-26 13:48 UTC, imanovmarat commented on src/services/reducers/modal.js
> +    case INGREDIENT_DETAILS_SET_STATUS: {
Сделано 👌

2021-07-26 14:06 UTC, imanovmarat commented on src/services/reducers/index.js
> +    case CHANGE_SELECTED_INGREDIENTS_ORDER: {
Сделано 👌

2021-07-26 14:08 UTC, imanovmarat commented on src/components/App/App.tsx
>    const [isIngredientDetailsModalOpen, setIsIngredientDetailsModalOpen] = useState(false)
Сделано 👌

2021-07-26 14:10 UTC, imanovmarat commented on src/components/App/App.tsx
> +    console.log('itemId ', itemData)
Сделано 👌

2021-07-26 14:35 UTC, imanovmarat commented on src/components/IngredientDetails/IngredientDetails.js
Не совсем понял, что я должен вынести в отдельный файл?

2021-07-26 18:04 UTC, AygulMalikova requested changes
Отлично! Вы исправили немало ошибок, и вы движетесь в правильном направлении!
Осталось исправить одну ошибку и ваша работа будет принята. Удачи!

2021-07-26 18:04 UTC, AygulMalikova commented on src/components/IngredientDetails/IngredientDetails.js
@imanovmarat Тип `{
                                              _id: PropTypes.string.isRequired,
                                              type: PropTypes.string.isRequired,
                                              proteins: PropTypes.number.isRequired,
                                              fat: PropTypes.number.isRequired,
                                              carbohydrates: PropTypes.number.isRequired,
                                              calories: PropTypes.number.isRequired,
                                              price: PropTypes.number.isRequired,
                                              name: PropTypes.string.isRequired,
                                              image: PropTypes.string.isRequired,
                                              image_large: PropTypes.string.isRequired,
                                            }`, который дублируется в нескольких местах

2021-07-27 08:14 UTC, AygulMalikova commented
Ваша работа принята, я вас поздравляю! Все ошибки исправлены и все условия задания выполнены. У вас отличный код, поделенный на компоненты. Так держать! Еще раз поздравляю и желаю вам дальнейших успехов!

2021-07-27 08:16 UTC, merged